### ISSUE TITLE
Don't trigger release when no code was changed

### ISSUE THREAD

**Issue by Lenni009** [NMSCD/Coordinate-Conversion#5]
@Khaoz-Topsy picking up from #3, we can discuss the issue here.

**The problem**

There shouldn't be a version bump and subsequent new npm release when no code was changed, e.g. when the readme was updated or when tests were edited.

**The solution**

We can use the `paths` or `paths-ignore` option in our CI/CD workflows to specify whether something should run, based on which files were edited. Syntax for this can be found in the [GitHub Docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths)

The question is whether we use `paths` or `paths-ignore`.

As stated in the docs, we can also negate a pattern. I think with this, using `paths` requires the least amount of thinking: If a file is listed, it will trigger the workflow. As you suggested, we can use `src/**/*` to glob all relevant ts files. We can also add `!src/**/*.spec.*` to exclude the test files.

An alternative solution to this would be to put tests into their own `tests` folder, and just exclude that (or put it outside of src entirely)

**Comment by Khaoz-Topsy** [comment]
Nice layout of the problem and solution 😋. I think it is worth it to add `!src/**/*.spec.*`  like you suggested. I am not a fan of placing the tests in their own folder or outside of src. I haven't tried placing tests outside of src, I assume it wouldn't work but I also can't see why it shouldn't 😅

**Comment by Lenni009** [comment]
Done with #7, let's see if this works
